name: 功能请求🙋‍♂️
description: 功能请求
labels:
  - 'Feature Request'
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间正确填写这份功能请求报告。

  - type: textarea
    id: what
    attributes:
      label: 功能描述
      description: |
        描述所要实现的功能
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他补充描述
      description: |
        其他补充描述