name: 'Commit CI'

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Pack plugin'
        run: |
          python pack.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.zip