name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: 'Pack plugin'
        run: |
          python pack.py
      - name: Create GitHub release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} ./dist/*.zip -t "Release ${{ github.ref_name }}" --generate-notes -d